### ISSUE TITLE
pwnenv: 動作確認

### ISSUE THREAD

**Issue by peloeil** [peloeil/ctfenv#1]
- [x] ropr
- [x] python
- [x] pwntools
- [x] ptrlib
- [x] rp++
- [x] radare2
- [x] pwndbg
- [x] gef

**Comment by peloeil** [comment]
ちゃんと warning 消せたら色が着くのかな
```
 checksec chall
Warning: _curses.error: setupterm: could not find terminfo database

Terminal features will not be available.  Consider setting TERM variable to your current terminal name (or xterm).
[*] '/home/peloeil/src/simpleoverwrite/chall'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
```

**Comment by peloeil** [comment]
gef はなんで動かないのか
```
(gdb) gef
Traceback (most recent call last):
  File "/home/peloeil/tools/.gdbinit-gef.py", line 11715, in <module>
    reset()
  File "/home/peloeil/tools/.gdbinit-gef.py", line 178, in reset
    gef.setup()
  File "/home/peloeil/tools/.gdbinit-gef.py", line 11649, in setup
    self.reinitialize_managers()
  File "/home/peloeil/tools/.gdbinit-gef.py", line 11644, in reinitialize_managers
    self.session = GefSessionManager()
  File "/home/peloeil/tools/.gdbinit-gef.py", line 11189, in __init__
    self.constants[constant] = which(constant)
  File "/home/peloeil/tools/.gdbinit-gef.py", line 1889, in which
    raise FileNotFoundError(f"Missing file `{program}`")
FileNotFoundError: Missing file `file`
```

**Comment by peloeil** [comment]
pwndbg は動くけど何かエラーが出ている？
```
(gdb) dbg
******
Your encoding (ANSI_X3.4-1968) is different than UTF-8. pwndbg might not work properly.
You might try launching GDB with:
    LC_CTYPE=C.UTF-8 gdb
If that does not work, make sure that en_US.UTF-8 is uncommented in /etc/locale.gen and that you called `locale-gen` command
******
pwndbg: loaded 154 pwndbg commands and 42 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $base, $ida GDB functions (can be used with print/break)
Traceback (most recent call last):
  File "/home/peloeil/tools/pwndbg/gdbinit.py", line 74, in <module>
    import pwndbg  # noqa: F401
  File "/home/peloeil/tools/pwndbg/pwndbg/__init__.py", line 88, in <module>
    config_mod.init_params()
  File "/home/peloeil/tools/pwndbg/pwndbg/gdblib/config.py", line 163, in init_params
    Parameter(p)
  File "/home/peloeil/tools/pwndbg/pwndbg/gdblib/config.py", line 49, in __init__
    self.value = param.value
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
------- tip of the day (disable with set show-tips off) -------
GDB's follow-fork-mode parameter can be used to set whether to trace parent or child after fork() calls
pwndbg>
```

**Comment by peloeil** [comment]
sudo が使えない。sudo が使えないので /etc/sudoers も確認できない。なぜか sudo グループに入っていないことが原因そう

**Comment by peloeil** [comment]
`export LC_CTYPE=C.UTF-8` とすれば pwndbg は動いた

**Comment by peloeil** [comment]
`file` コマンドを入れれば gef は動いた

**Comment by peloeil** [comment]
`make` を入れたら radare2 は動いた
