### ISSUE TITLE
pwnenv: Terminal features will not be available.  Consider setting TERM variable to your current terminal name (or xterm).

### ISSUE THREAD

**Issue by peloeil** [peloeil/ctfenv#3]
```
$ checksec ./chall
Warning: _curses.error: setupterm: could not find terminfo database

Terminal features will not be available.  Consider setting TERM variable to your current terminal name (or xterm).
[*] '/home/peloeil/src/simpleoverwrite/chall'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
```
本来は最後の5行は色がついて表示されるはず。上2つのメッセージを解消すれば色が付きそう。

**Comment by peloeil** [comment]
環境によっては、エラーになって `checksec` が実行できないこともあるらしい。

**Comment by eno1220** [comment]
Dockerの環境に入り`checksec`を実行したところ、以下のようなエラーが発生しました。
なお、OSは`Ubuntu 24.04`で、デフォルトのターミナル及びWarp Terminalで試しましたが、どちらの環境でも同様のエラーが発生しました。
```bash
Warning: _curses.error: setupterm: could not find terminfo database

Terminal features will not be available.  Consider setting TERM variable to your current terminal name (or xterm).
Traceback (most recent call last):
  File "/home/eno1220/.venv/bin/checksec", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/eno1220/.venv/lib/python3.12/site-packages/pwnlib/commandline/common.py", line 29, in main
    import pwnlib.commandline.main
  File "/home/eno1220/.venv/lib/python3.12/site-packages/pwnlib/commandline/main.py", line 5, in <module>
    from pwnlib.commandline import asm
  File "/home/eno1220/.venv/lib/python3.12/site-packages/pwnlib/commandline/asm.py", line 11, in <module>
    from pwn import *
  File "/home/eno1220/.venv/lib/python3.12/site-packages/pwn/__init__.py", line 4, in <module>
    from pwn.toplevel import *
  File "/home/eno1220/.venv/lib/python3.12/site-packages/pwn/toplevel.py", line 92, in <module>
    colored_traceback.add_hook()
  File "/home/eno1220/.venv/lib/python3.12/site-packages/colored_traceback/colored_traceback.py", line 78, in add_hook
    colorizer = Colorizer(style, colors, debug)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eno1220/.venv/lib/python3.12/site-packages/colored_traceback/colored_traceback.py", line 64, in __init__
    self.formatter = _determine_formatter(style, colors, debug)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eno1220/.venv/lib/python3.12/site-packages/colored_traceback/colored_traceback.py", line 38, in _determine_formatter
    colors = colors or _get_term_color_support()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eno1220/.venv/lib/python3.12/site-packages/colored_traceback/colored_traceback.py", line 34, in _get_term_color_support
    curses.setupterm()
_curses.error: setupterm: could not find terminfo database
```

**Comment by eno1220** [comment]
Dockerのシェルに入った状態で
```shell
export TERMINFO="/usr/lib/terminfo"
```
と`TERMINFO`の値を設定すると、`checksec`が正しく実行され、色がついた状態で表示できるようになりました。
